# Generated by Django 5.0.4 on 2024-05-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("desc", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name_plural": "Announcements",
                "db_table": "Announcement",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Departments", "db_table": "Department",},
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Levels", "db_table": "Level",},
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=500)),
            ],
            options={"verbose_name_plural": "Semesters", "db_table": "Semester",},
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Sessions", "db_table": "Session",},
        ),
        migrations.CreateModel(
            name="CourseRepresentative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=14)),
                (
                    "pics",
                    models.ImageField(
                        blank=True,
                        default="img/kadlogo.png",
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.department",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.level",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CourseRepresentatives",
                "db_table": "CourseRepresentative",
            },
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("links", models.CharField(max_length=500)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.department",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.level",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.semester",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Links", "db_table": "Links",},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=500)),
                ("unit", models.IntegerField(default=2)),
                ("desc", models.CharField(max_length=1000)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.department",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.level",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.semester",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Courses", "db_table": "Course",},
        ),
        migrations.CreateModel(
            name="SessionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("links", models.CharField(max_length=500)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Odfelbot_API.session",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Session Link",
                "db_table": "Session Link",
            },
        ),
    ]
