# Generated by Django 5.0.4 on 2024-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Odfelbot_API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="date_created",
            field=models.DateField(auto_now=True),
        ),
    ]
