# Generated by Django 5.0.4 on 2024-05-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Odfelbot_API", "0003_alter_links_links_alter_sessionlink_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="links",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Odfelbot_API.course",
            ),
            preserve_default=False,
        ),
    ]
