# Generated by Django 5.0.4 on 2024-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Odfelbot_API", "0005_remove_courserepresentative_pics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="desc",
            field=models.TextField(max_length=1000),
        ),
    ]
